version: 1
services:
  - type: web
    name: loanproject
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn loanproject.wsgi --bind 0.0.0.0:$PORT"
    plan: free
    routes:
      - type: basic
        path: /
    static:
      - url: /static
        dir: staticfiles
      - url: /media
        dir: media
