version: 1
services:
  - type: web
    name: loanproject
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn loanproject.wsgi --log-file -"
    plan: free
    routes:
      - type: basic
        path: /
    static:
      - url: /static
        dir: staticfiles
      - url: /media
        dir: media
