# Generated by Django 5.0.7 on 2024-07-18 10:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='default_name', max_length=255)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=150, unique=True)),
                ('passw', models.CharField(max_length=128)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.position')),
            ],
        ),
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('customer', models.CharField(default='', max_length=255)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('principal', models.IntegerField()),
                ('installments', models.IntegerField()),
                ('interest', models.IntegerField()),
                ('status', models.CharField(default='', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.usert')),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
