# Generated by Django 5.0.7 on 2024-07-18 12:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_position_usert_loantype_delete_account_delete_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('customer', models.CharField(default='', max_length=255)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('principal', models.IntegerField()),
                ('perday', models.IntegerField()),
                ('installments', models.IntegerField()),
                ('interest', models.IntegerField()),
                ('status', models.CharField(default='', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.usert')),
            ],
        ),
        migrations.DeleteModel(
            name='LoanType',
        ),
    ]
