# Generated by Django 5.0.7 on 2024-07-18 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_loan_delete_loantype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='id',
            new_name='loanid',
        ),
    ]
