# Generated by Django 5.0.7 on 2024-07-21 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_payment_paid_payment_status_alter_payment_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usert',
            old_name='passw',
            new_name='apppass',
        ),
        migrations.RenameField(
            model_name='usert',
            old_name='user',
            new_name='appuser',
        ),
    ]
