# Generated by Django 5.0.7 on 2024-07-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_passw_usert_apppass_rename_user_usert_appuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
